# Generated by Django 5.0.4 on 2024-04-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.IntegerField()),
                ("adminId", models.CharField(max_length=12)),
                ("name", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="StuInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.IntegerField()),
                ("stuId", models.CharField(max_length=12)),
                ("name", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
                ("assignScore1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("assignScore2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("assignScore3", models.DecimalField(decimal_places=2, max_digits=5)),
                ("assignScore4", models.DecimalField(decimal_places=2, max_digits=5)),
                ("assignScore5", models.DecimalField(decimal_places=2, max_digits=5)),
                ("examScore1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("examScore2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("examScore3", models.DecimalField(decimal_places=2, max_digits=5)),
                ("predictScore1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("predictScore2", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="TeacherInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.IntegerField()),
                ("teacherId", models.CharField(max_length=12)),
                ("name", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
            ],
        ),
    ]
