# Generated by Django 5.0.4 on 2024-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WarningSystem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignName", models.CharField(max_length=32, verbose_name="作业名称")),
                ("assignDesc", models.CharField(max_length=256, verbose_name="作业描述")),
            ],
        ),
        migrations.CreateModel(
            name="ExamInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("examName", models.CharField(max_length=32, verbose_name="考试名称")),
                ("examDesc", models.CharField(max_length=256, verbose_name="考试描述")),
            ],
        ),
        migrations.AlterField(
            model_name="admininfo",
            name="adminId",
            field=models.CharField(max_length=5, verbose_name="管理员工号"),
        ),
        migrations.AlterField(
            model_name="admininfo",
            name="name",
            field=models.CharField(max_length=32, verbose_name="管理员姓名"),
        ),
        migrations.AlterField(
            model_name="admininfo",
            name="password",
            field=models.CharField(default="123456", max_length=64, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="admininfo",
            name="role",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="assignScore1",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="作业成绩1"
            ),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="assignScore2",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="作业成绩2"
            ),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="assignScore3",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="作业成绩3"
            ),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="assignScore4",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="作业成绩4"
            ),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="assignScore5",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="作业成绩5"
            ),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="examScore1",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="考试成绩1"
            ),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="examScore2",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="考试成绩2"
            ),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="examScore3",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="期末成绩"
            ),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="name",
            field=models.CharField(max_length=32, verbose_name="学生姓名"),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="password",
            field=models.CharField(default="123456", max_length=64, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="predictScore1",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="预测成绩1"
            ),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="predictScore2",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="预测成绩2"
            ),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="role",
            field=models.IntegerField(default=0, verbose_name="角色标签"),
        ),
        migrations.AlterField(
            model_name="stuinfo",
            name="stuId",
            field=models.CharField(max_length=12, verbose_name="学生学号"),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="name",
            field=models.CharField(max_length=32, verbose_name="教师姓名"),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="password",
            field=models.CharField(default="123456", max_length=64, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="role",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="teacherId",
            field=models.CharField(max_length=12, verbose_name="教师工号"),
        ),
    ]
