# Generated by Django 5.0.4 on 2024-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WarningSystem", "0002_assigninfo_examinfo_alter_admininfo_adminid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stuinfo",
            name="stuId",
            field=models.CharField(max_length=12, unique=True, verbose_name="学生学号"),
        ),
    ]
