# Generated by Django 5.0.4 on 2024-04-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WarningSystem", "0003_alter_stuinfo_stuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admininfo",
            name="adminId",
            field=models.CharField(max_length=5, unique=True, verbose_name="管理员工号"),
        ),
        migrations.AlterField(
            model_name="teacherinfo",
            name="teacherId",
            field=models.CharField(max_length=12, unique=True, verbose_name="教师工号"),
        ),
    ]
